src/Items/urls.py
from django.conf.urls import url
from django.contrib import admin


from Items.views import displayItem


urlpatterns = [
    url(r'^.+', displayItem)
]

src/Pricr/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


from Items.views import createStore, createItem, itemListView, createStoreName, index, displayStore



urlpatterns = [
	
    url(r'^admin/', admin.site.urls),
    url(r'^items/', include('Items.urls')),
    url(r'^stores/.+', displayStore),
    url(r'^$', index),
    url(r'^createStore$', createStore),
    url(r'^createStoreName$', createStoreName),
    url(r'^createItem$', createItem),
    url(r'^itemListView$', itemListView),
]    

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/Items/models.py
from django.db import models
import os
from Pricr.settings import BASE_DIR, STATIC_ROOT
import geocoder

# Create your models here.
class Item(models.Model):
	def user_directory_path(instance, filename):
    	# file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
   		return 'user_{0}/{1}'.format(instance.user.id, filename)


	item_price				=	models.DecimalField(max_digits=10, decimal_places=2,)
	item_name				=	models.CharField(max_length=50, unique=True)
	store					= 	models.ForeignKey('Store', on_delete=models.CASCADE,)	# This should be changed so that it relates to a db of stores
	proof_of_price			=	models.ImageField(upload_to='static/imageUploads/proof_of_price', height_field=None, width_field=None, max_length=100,) #FIXME images are not properly stored
	is_sale_price			=	models.BooleanField(default=False,)
	datetime_of_submission	=	models.DateTimeField(auto_now_add=True)
	image_of_item			=	models.ImageField(upload_to='static/imageUploads/image_of_tem', height_field=None, width_field=None, max_length=100, null=True) #FIXME images are not properly stored
	#user_changed_by	=	user model	

	def __str__(self):
		return "item name: " +str(self.item_name)+" id: "+str(self.id)	

class UpdateInformation(models.Model):
	item				=	models.ForeignKey('Item', related_name='UpdateInformation')
	datetime_of_update	=	models.DateTimeField(auto_now_add=True)
	#changes made
	#user_changed_by	=	user model	

class ItemAttribute(models.Model):
	item 			= 	models.ForeignKey('Item', related_name='ItemAttributes')
	attributeName	=	models.CharField(max_length=50, unique=True)
	attributeValue	=	models.CharField(max_length=100)
	attributeUnit	=	models.CharField(max_length=20, unique=True)


class Store(models.Model):
	name 			= 	models.ForeignKey('StoreName', on_delete=models.CASCADE)
	store_location	=	models.CharField(max_length=50,) #This should be replaced with a custom field that uses a location library to accurately place each store
	datetime_of_submission	=	models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return str(self.name)+ ' at '+ str(self.store_location)



class StoreName(models.Model):
	name 			= 	models.CharField(max_length=50, unique=True)
	datetime_of_submission	=	models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return str(self.name)


class Geocode(object):
	""" A location using the Geocoder library """

	def __init__(self, geocode_str, given_geocode_str):
		self.geocode_str=geocode_str
		self.given_geocode_str=given_geocode_str



class GeocodeField(models.CharField):
	description = "A specific location on earth"

	def __init__(self, *args, **kwargs):
		super(HandField, self).__init__(*args, **kwargs)

		

src/Items/forms.py
from django import forms

from .models import Item, Store, StoreName

from django.template.loader import render_to_string


class NewItemForm(forms.ModelForm):
	store = forms.ModelChoiceField(Store.objects)
	
	class Meta:
		model = Item
		fields= [
			"proof_of_price", "item_price", "item_name", "store", "is_sale_price", "image_of_item",
		]
	def __init__(self, *args, **kwargs):
		super(NewItemForm, self).__init__(*args, **kwargs)

		self.fields['item_price'].widget.attrs.update({'class' : 'form-control'})
		self.fields['item_name'].widget.attrs.update({'class' : 'form-control'})
		self.fields['store'].widget.attrs.update({'class' : 'form-control'})
		self.fields['proof_of_price'].widget.attrs.update({'class' : 'form-control'})
		self.fields['is_sale_price'].widget.attrs.update({'class' : 'form-check-input'})
		self.fields['image_of_item'].widget.attrs.update({'class' : 'form-control'})

class SearchForm(forms.Form):
	search = forms.CharField()

class NewStoreForm (forms.ModelForm):
	class Meta:
		model = Store
		fields= {
			"name", "store_location"
		}
	def __init__(self, *args, **kwargs):
		super(NewStoreForm, self).__init__(*args, **kwargs)
		self.fields['name'].widget.attrs.update({'class' : 'form-control'})
		self.fields['store_location'].widget.attrs.update({'class' : 'form-control'})



class NewStoreNameForm(forms.ModelForm):
	class Meta:
		model = StoreName
		fields= {
			"name"
		}

	def __init__(self, *args, **kwargs):
		super(NewStoreNameForm, self).__init__(*args, **kwargs)
		self.fields['name'].widget.attrs.update({'class' : 'form-control'})

src/Items/controllers.py
from .models import Item
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector

def search(terms):
	# Leave this code, it is a more advaced search that sqlite databases do not support,
	# but postgres ones do, so we'll use it when we switch to the postgres database
	vector = SearchVector('item_name', weight='A') +\
	SearchVector('store__name__name', weight='A') +\
	SearchVector('store__store_location', weight='C')

	query = SearchQuery(terms)

	results = Item.objects.annotate(rank=SearchRank(vector, query)).filter(rank__gte=0.3)#.order_by('rank')

	# queries = terms.split()

	# results = None

	# for query in queries:
	# 	if not results:
	# 		results = Item.objects.filter(item_name__icontains=query) |\
	# 		Item.objects.filter(store__name__name__icontains=query) |\
	# 		Item.objects.filter(item_price__icontains=query) |\
	# 		Item.objects.filter(store__store_location__icontains=query)
	# 	else:
	# 		results = results | Item.objects.filter(item_name__icontains=query) |\
	# 		Item.objects.filter(store__name__name__icontains=query) |\
	# 		Item.objects.filter(item_price__icontains=query) |\
	# 		Item.objects.filter(store__store_location__icontains=query)

	if results is None or not results.exists():
		return 'Nothing'

	return results

def html_readable(queryset):
	html_readable_version = list()

	for item in queryset:
		result = {
			'price': item.item_price,
			'name': item.item_name,
			'store_name': item.store.name.name,
			'store_location': item.store.store_location,
			'is_sale_price': item.is_sale_price,
			'proof_of_price_url': item.proof_of_price.url
		}

		html_readable_version.append(result)

	return html_readable_version

src/Items/views.py
from django.shortcuts import render
from django.views.generic import View
# Create your views here
from .forms import NewItemForm, SearchForm, NewStoreForm, NewStoreNameForm
from .models import Item, Store
from .controllers import search 
from django.template import RequestContext, Template
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
import geocoder

def createStoreName(request):
	if request.POST:
		newStoreNameForm = NewStoreNameForm(request.POST)
		if newStoreNameForm.is_valid():
			newStoreNameForm.save()
			return HttpResponseRedirect("/")
	else:
		newStoreNameForm = NewStoreNameForm(None)

	context = {
		"form": newStoreNameForm,
	}
	if newStoreNameForm.is_valid():
		newStoreNameForm.save()
		return render(request, "items/createStoreName.html", context)

	return render(request, "items/createStoreName.html", context)

def createStore(request):
	if request.POST:
		newStoreForm = NewStoreForm(request.POST)
		if newStoreForm.is_valid():
			newStoreForm.save()
			return HttpResponseRedirect("/")
	else:
		newStoreNameForm = NewStoreNameForm()
		newStoreForm = NewStoreForm(None)

	context = {
		"newStoreForm": newStoreForm,
		"newStoreNameForm": newStoreNameForm,
	}
	if newStoreForm.is_valid():
		newStoreForm.save()
		return render(request, "items/createStore.html", context)

	return render(request, "items/createStore.html", context)

def itemListView(request):
	context= {
		"object_list" : list(),
		"title" : "Item List",
		"is_search" : False,
	}
	
	for queryset in Item.objects.all():
		print(queryset)
		item_vals = {
			"list":	True,
			"item_name" : queryset.item_name,
			"store" : queryset.store,
			"store_id": queryset.store.id,
			"item_price" : queryset.item_price,
			"proof_of_price" : queryset.proof_of_price,
			"is_sale_price" : queryset.is_sale_price,
			"id": queryset.id,
		}

		context["object_list"].append(item_vals)

	return render(request, "items/itemListView.html", context)


def createItem(request):
	if request.POST:
		newItemForm = NewItemForm(request.POST, request.FILES)
		newStoreForm = NewStoreForm()
		newStoreNameForm = NewStoreNameForm()
		if newItemForm.is_valid():
			newItemForm.save()
			return HttpResponseRedirect("/")
	else:
		newItemForm = NewItemForm(None)
		newStoreForm = NewStoreForm(None)
		newStoreNameForm = NewStoreNameForm(None)


	if newItemForm.is_valid():
		newItemForm.save()
				
		return render(request, "items/createItem.html", context)

	context = {
		"newStoreForm": newStoreForm,
		"newStoreNameForm": newStoreNameForm,
		"newItemForm": newItemForm
	}
	
	return render(request, "items/createItem.html", context)

def index(request):
	newItemForm = NewItemForm()
	newStoreForm = NewStoreForm()
	newStoreNameForm = NewStoreNameForm()

	searchForm = SearchForm(request.GET or None)

	context = {
		"newItemForm": newItemForm,
		"newStoreForm": newStoreForm,
		"newStoreNameForm": newStoreNameForm
	}

	if searchForm.is_valid():
		context['object_list'] = search(searchForm.cleaned_data['search'])
		if len(object_list)==0:
			context['failed_to_find']="Your search did not return any results"
			context['is_search']= True

		return render(request,"items/itemListView.html", context)

	return render(request,"items/index.html", context)

def displayItem(request):
	try:
		query=request.path
		print(query)
		query=query.replace("/items/", "")
		print(query)
		queryset = Item.objects.get(id=query) 
		print(queryset)
		context= {
			"is_item": True,
			"item_name" : queryset.item_name,
			"store" : queryset.store,
			"item_price" : queryset.item_price,
			"proof_of_price" : queryset.proof_of_price,
			"is_sale_price" : queryset.is_sale_price,	
		}
	except:
		context={
			"failed_to_find": "We couldn't find the item you were looking for. If you believe this item should exist, please email a developer"
		}

	return render(request, "items/displayItem.html", context)


def displayStore(request):
	
	try:
		query=request.path
		query=query.replace("/stores/", "")
		queryset = Store.objects.get(id=query) 
		print("querryset",queryset)
		context= {
			"is_item": False,
			"store_location" : queryset.store_location,
			"store" : queryset.name,
		}
	except:
		context={
			"failed_to_find": "We couldn't find the store you were looking for. If you believe this store should exist, please email a developer"
		}

	return render(request, "items/displayItem.html", context)

src/Items/templates/items/createItem.html
<!--DOCKTYPE html -->

<html>
	{% include "items/header.html" %}  
	<body>
		<div class="page-header">
			<h1 class="text-center display-4">Submit a new Item</h1>
		</div>

	{% include "items/createItemForm.html" %}

	</body>
				<br>
		<br>
				<br>
		<br>
				<br>
		<br>
				<br>
		<br>
				<br>
		<br>
				<br>
		<br>
				<br>
		<br>

	{% include "items/footer.html" %}
</html>

src/Items/templates/items/createItemForm.html
		<div class="container">
			<div class="jumbotron">
					<a href=#createStore data-toggle="collapse"  class="secondary-text-color">
						Your store not in the system? Click here
					</a>

					<div id="createStore" class="collapse in">
						
						<a href=#createStoreName data-toggle="collapse"  class="secondary-text-color">
						Your store brand/name not in the system? Click here
						</a>

						<div id="createStoreName" class="collapse in">
							<form action="createStoreName" method="post"	>
								{% csrf_token %}
								

								{{ newStoreNameForm.as_p}}
								<input type='submit' value='Submit Store name' class="accent-color btn"/>
							</form>
						</div>

						<form action="createStore" method="POST"	>
							{% csrf_token %}
							

							{{ newStoreForm.as_p}}
							<input type='submit' value='Submit Store' class="accent-color btn" />
						</form>
					</div>

					</br>
					</br>

					<form action="createItem" method="POST" enctype="multipart/form-data">
						{% csrf_token %}						

						<p><label for="id_proof_of_price">Image proof of price:</label> <input class="form-control" id="id_proof_of_price" name="proof_of_price" type="file" required=""></p>
						<p><label for="id_item_price">Item price:</label> <input class="form-control" id="id_item_price" name="item_price" step="0.01" type="number" required=""></p>
						<p><label for="id_item_name">Item name:</label> <input class="form-control" id="id_item_name" maxlength="50" name="item_name" type="text" required=""></p>

						<p>
							<label for="id_store">Store:</label>
							{{ newItemForm.store }}
						</p>

						<p>
							<label for="id_is_sale_price">Is sale price:</label> 
							<input id="id_is_sale_price" name="is_sale_price" type="checkbox">
						</p>

						<p>
							<input type="submit" value="Submit Item" class="accent-color btn">
						</p>
					</form>
				<br>
				<br>
			</div>
		</div>

src/Items/templates/items/createStore.html
<!--DOCKTYPE html -->

<html>
		{% include "items/header.html" %}  
		<div class="page-header">
			<h1 class="text-center display-4">Submit a new Store</h1>
		</div>
	<body>
		<div class="container">
			<div class="jumbotron">
					
					<a href=#createStoreName data-toggle="collapse"  class="secondary-text-color">
					Your store brand/name not in the system? Click here
					</a>

					<div id="createStoreName" class="collapse in">
						<form action="createStoreName" method="post"	>
							{% csrf_token %}
							

							{{ newStoreNameForm.as_p }}
							<input type='submit' value='Submit Store name' class="accent-color btn" />
						</form>
					</div>

					<form action="createStore" method="POST"	>
						{% csrf_token %}
						

						{{ newStoreForm.as_p }}
						<input type='submit' value='Submit Store' class="accent-color btn"/>
					</form>
				</div>

				<br>
				<br>
			</div>
		</div>
		<br>
		<br>
	</body>
			<br>
		<br>
				<br>
		<br>
				<br>
		<br>
				<br>
		<br>
				<br>
		<br>
				<br>
		<br>
				<br>
		<br>
				<br>
		<br>
				<br>
		<br>

	{% include "items/footer.html" %}
</html>

src/Items/templates/items/createStoreName.html
<!--DOCKTYPE html -->

<html>
		{% include "items/header.html" %}  
	<hr>
	<br>
	<br>
	<br>
	<body>
		<div class="container">
			<div class="jumbotron">
				<form action="createStoreName" method="POST">
					{% csrf_token %}
					{{ form.as_p }}
					<input type='submit' value="Create new Store Name" />
				</form>

			</div>
		</div>
		<br>
		<br>
		<!-- bootstrap imports-->
	</body>
</html>

src/Items/templates/items/displayItem.html
<!--DOCKTYPE html -->

<html>
	{% include "items/header.html" %}  

	<body>

		<div class="container">
			<div class="page-header">
				<h1 class="text-center display-4">{{ title }}</h1>
			</div>

			<div class="row justify-content-center">
				<div class="col-md-10">
					<div class="center jumbotron light-primary-color">
						
						<div class="row">
							<div class="col-md-7">
								<h2><span class="alert-danger">{{ failed_to_find }}</span></h2>

								{% if is_item %}
									<p><small class="secondary-text-color">Item: </small> {{ item_name }}</p>
									<p><small class="secondary-text-color">Price: </small> ${{ item_price }}<sup>¢</sup></p>
									<p><small class="secondary-text-color">Store: </small> {{ store }}</p>
									{% if is_sale_price %}
											<h6><em>This is a sale price</em></h6>
									{% endif %}

								{% else %}
									<p><small class="secondary-text-color">Store brand: </small> {{ store }}</p>
									<p><small class="secondary-text-color">Store location: </small> {{ store_location }}</p>
								{% endif %}

							</div>
							<div class="col-md-5">
									<img style="float: right; max-height: 200px" src="{{ proof_of_price.url }}" class="img-responsive img-rounded">
							</div>
						</div>
						
						
					</div>
				</div>
			</div>
		</div>
	</body>
	{% include "items/footer.html" %}
</html>

src/Items/templates/items/footer.html
<footer>
	<nav class="navbar navbar-expand-lg navbar-light navbar-fixed-bottom default-primary-color ">
		<div class="container">
			<a class="navbar-brand" href="/">Pricetag Club</a>

			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" href="mailto:Max@Maxniebergall.com">Email a Developer</a>
				</li>				
			</ul>
		</div>
	</nav>
</footer>

src/Items/templates/items/forms.html
<form>
	{% csrf_token %}

	{{ form.as_p}}
	<input type='submit' value='Submit Item' />
</form>

src/Items/templates/items/header.html
<head>

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
		<meta charset="utf-8">
		<meta name="theme-color" content="#FFC107"><!--default-primary-color-->
		<meta http-equiv="Cache-control" content="public">
		<!-- If IE use the latest rendering engine -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge">

		<!-- Set the page to the width of the device and set the zoon level -->
		<meta name="viewport" content="width = device-width, initial-scale = 1">
		
		<!-- Select2 and Bootstrap adn JQuirry-->
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
		<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
		<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
		
		<script type="text/javascript">
 		 $('select').select2();
		</script>

		{% load static %}
		<link rel="stylesheet" href="{% static "main.css" %}">
		<link rel="shortcut icon" type="image/png" href="{% static "favicon.ico" %}"/>

		<title>Pricetag.club</title>
</head>
<header>
	<nav class="navbar navbar-expand-lg navbar-light default-primary-color ">
		<a class="navbar-brand" href="/"> <img class="img-responsive" src="{% static "Pricetagclub_logo_v4_withcolor.png" %}" height="60px" width="60px" alt="Pricetag Club"></a>

		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		
		<div class="collapse navbar-collapse" id="navbarText">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" href="/itemListView">Item List <span class="sr-only">(current)</span></a>
				</li>				
				
				<li class="nav-item active">
					<a class="nav-link" href="/createItem">New Item</a>
				</li>

				<li class="nav-item active">
					<a class="nav-link" href="/createStore">New Store</a>
				</li>
			</ul>

			<div class="col-md-5">
				<form method="GET" action="/" class="center form-inline">
					<input name="{{ search_form.search.name }}" id="{{ search_form.search.auto_id }}" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
					<button class="btn accent-color my-2 my-sm-0" type="submit">Search</button>
				</form>
			</div>
			
			<span class="navbar-text">
				Membership coming soon  
			</span>
			<a class="nav-link disabled btn btn-secondary" href="#"><span style="color:white">Login</span></a>
		</div>
	</nav>
</header>

src/Items/templates/items/home.html
hello --home.html

src/Items/templates/items/index.html
<!--DOCKTYPE html -->

<html>
	{% include "items/header.html" %}  
	<div class="page-header">
			<h2 class="text-center">Pricetag Club- Find prices, share and review products and services</h2>
		</div>
	<body>	
		{% include "items/createItemForm.html" %}
	</body>
		<br>
		<br>
		<br>
		<br>
	{% include "items/footer.html" %}  
</html>

src/Items/templates/items/itemListView.html
<!--DOCKTYPE html -->

<html>
	{% include "items/header.html" %}  

	<body>

		<div class="container">
			<div class="page-header">
				<h1 class="text-center display-4">{{ title }}</h1>
			</div>

			<div class="row justify-content-center">
				<div class="col-md-10">
					<div class="center jumbotron light-primary-color">
						
						<h2><span class="alert-danger">{{ failed_to_find }}</span></h2>

						{% if not is_search %}	
							{% for obj in object_list %}

								<div class="row">
									<div class="col-md-7">
										<a href="/items/{{ obj.id }}"><small class="secondary-text-color">Item: </small> {{ obj.item_name }}</a>
										<p><small class="secondary-text-color">Price: </small> ${{ obj.item_price }}<sup>¢</sup></p>
										<a href="/stores/{{ obj.store_id }}"><p><small class="secondary-text-color">Store: </small> {{ obj.store }}</p></a>
										
										{% if obj.is_sale_price %}
										<h6><em>This is a sale price</em></h6>
										{% endif %}
										
									</div>

									<div class="col-md-5">
										<img style="float: right; max-height: 200px" src="{{ obj.proof_of_price.url }}" class="img-responsive img-rounded">
									</div>
								</div>
								
								<!-- <br/> -->
								<hr/>
								<!-- <br/> -->
							{% endfor %}
						{% endif %}
						
					</div>
				</div>
			</div>
		</div>
	</body>
	{% include "items/footer.html" %}
</html>

src/Items/templates/items/search-results.html
<!--DOCKTYPE html -->

<html>
	{% include "items/header.html" %}  

	<body>

		<h4 class = "text-center display-4">Search Results</h4>
		<div class="container">
			<div class="jumbotron light-primary-color">				
				{% if search != "" and search != "Nothing" %}

					{% for result in search %}
						<div class="row ">
							<div class="col-md-7">
								<p><small class="secondary-text-color">Item: </small> {{ result.name }}</p>
								<p><small class="secondary-text-color">Price: </small> ${{ result.price }}<sup>¢</sup></p>
								<p><small class="secondary-text-color">Store: </small> {{ result.store_name }} at {{ result.store_location }}</p>
								
								{% if result.is_sale_price %}
								<h6><em>This is a sale price</em></h6>
								{% endif %}
								
							</div>

							<div class="col-md-5">
								<img style="float: right; max-height: 200px" src="{{ result.proof_of_price_url }}" class="img-responsive img-rounded">
							</div>
						</div>

						<hr>
					{% endfor %}

				{% elif search == "Nothing" %}
					<h1 class="display-4 text-center">Your search did not return any results</h1>
				{% endif %}

				<br>
			</div>
		</div>
	</body>
		{% include "items/footer.html" %}  
</html>